/// All combination recipes for the game.
/// Each entry: { 'inputs': [sorted emoji list], 'output': emoji, 'name': label }
/// Inputs with 2 or 3 emojis are supported.
const List<Map<String, dynamic>> kRecipes = [
  // ── Tier 1: Basic combinations (starters → new basics) ──────────────────
  {'inputs': ['🔥', '💧'], 'output': '💨', 'name': 'Steam'},
  {'inputs': ['🔥', '🌍'], 'output': '🌋', 'name': 'Volcano'},
  {'inputs': ['💧', '🌍'], 'output': '🌱', 'name': 'Plant'},
  {'inputs': ['💨', '🌍'], 'output': '🌪️', 'name': 'Tornado'},
  {'inputs': ['🔥', '💨'], 'output': '⚡', 'name': 'Lightning'},
  {'inputs': ['💧', '💨'], 'output': '❄️', 'name': 'Ice'},
  {'inputs': ['🌍', '🌍'], 'output': '⛰️', 'name': 'Mountain'},
  {'inputs': ['💧', '💧'], 'output': '🌊', 'name': 'Ocean'},
  {'inputs': ['🔥', '🔥'], 'output': '☀️', 'name': 'Sun'},
  {'inputs': ['💨', '💨'], 'output': '🌀', 'name': 'Cyclone'},

  // ── Tier 2: Combinations using Tier 1 results ────────────────────────────
  {'inputs': ['🌱', '🌊'], 'output': '🌴', 'name': 'Palm Tree'},
  {'inputs': ['🌱', '☀️'], 'output': '🌸', 'name': 'Flower'},
  {'inputs': ['🌱', '❄️'], 'output': '🎄', 'name': 'Pine Tree'},
  {'inputs': ['🌱', '🌱'], 'output': '🌿', 'name': 'Bush'},
  {'inputs': ['🌱', '🌍'], 'output': '🍄', 'name': 'Mushroom'},
  {'inputs': ['⛰️', '🔥'], 'output': '🪨', 'name': 'Rock'},
  {'inputs': ['⛰️', '❄️'], 'output': '🏔️', 'name': 'Snow Mountain'},
  {'inputs': ['🌊', '☀️'], 'output': '🏖️', 'name': 'Beach'},
  {'inputs': ['🌊', '❄️'], 'output': '🧊', 'name': 'Iceberg'},
  {'inputs': ['☀️', '❄️'], 'output': '🌈', 'name': 'Rainbow'},
  {'inputs': ['⚡', '💧'], 'output': '🌧️', 'name': 'Rain'},
  {'inputs': ['⚡', '🌍'], 'output': '💎', 'name': 'Crystal'},
  {'inputs': ['🌪️', '💧'], 'output': '🌩️', 'name': 'Storm'},
  {'inputs': ['🌋', '💧'], 'output': '🪨', 'name': 'Obsidian'},
  {'inputs': ['🌋', '❄️'], 'output': '⛰️', 'name': 'Mountain (cool)'},

  // ── Tier 3: Life & Creatures ──────────────────────────────────────────────
  {'inputs': ['🌱', '⚡'], 'output': '🐛', 'name': 'Worm'},
  {'inputs': ['🌱', '🌧️'], 'output': '🐌', 'name': 'Snail'},
  {'inputs': ['🌊', '🌱'], 'output': '🐟', 'name': 'Fish'},
  {'inputs': ['🌊', '🌸'], 'output': '🦈', 'name': 'Shark'},
  {'inputs': ['🐟', '🌊'], 'output': '🐬', 'name': 'Dolphin'},
  {'inputs': ['🐟', '🐟'], 'output': '🦑', 'name': 'Squid'},
  {'inputs': ['🌿', '☀️'], 'output': '🦋', 'name': 'Butterfly'},
  {'inputs': ['🌿', '🌧️'], 'output': '🐸', 'name': 'Frog'},
  {'inputs': ['🌿', '⚡'], 'output': '🐝', 'name': 'Bee'},
  {'inputs': ['🌴', '🌊'], 'output': '🐊', 'name': 'Crocodile'},
  {'inputs': ['🌴', '☀️'], 'output': '🦎', 'name': 'Lizard'},
  {'inputs': ['🏔️', '🌱'], 'output': '🐐', 'name': 'Goat'},
  {'inputs': ['🏔️', '❄️'], 'output': '🐺', 'name': 'Wolf'},
  {'inputs': ['🪨', '🌱'], 'output': '🦔', 'name': 'Hedgehog'},
  {'inputs': ['🌿', '🌿'], 'output': '🐇', 'name': 'Rabbit'},
  {'inputs': ['🐇', '🐇'], 'output': '🦊', 'name': 'Fox'},
  {'inputs': ['🦊', '🌿'], 'output': '🐻', 'name': 'Bear'},
  {'inputs': ['🐻', '❄️'], 'output': '🐼', 'name': 'Panda'},
  {'inputs': ['🐸', '🌊'], 'output': '🐢', 'name': 'Turtle'},
  {'inputs': ['🦋', '🌸'], 'output': '🌺', 'name': 'Hibiscus'},
  {'inputs': ['🐝', '🌸'], 'output': '🍯', 'name': 'Honey'},
  {'inputs': ['🌴', '🦎'], 'output': '🦕', 'name': 'Dinosaur'},
  {'inputs': ['🦕', '🌋'], 'output': '🐉', 'name': 'Dragon'},
  {'inputs': ['🐉', '🔥'], 'output': '🔮', 'name': 'Magic Orb'},

  // ── Tier 4: Human world ───────────────────────────────────────────────────
  {'inputs': ['🔥', '🪨'], 'output': '⚒️', 'name': 'Tools'},
  {'inputs': ['⚒️', '🌱'], 'output': '🏡', 'name': 'House'},
  {'inputs': ['🏡', '🏡'], 'output': '🏘️', 'name': 'Village'},
  {'inputs': ['🏘️', '🏘️'], 'output': '🏙️', 'name': 'City'},
  {'inputs': ['🏡', '⚒️'], 'output': '🏰', 'name': 'Castle'},
  {'inputs': ['⚒️', '💎'], 'output': '⚔️', 'name': 'Sword'},
  {'inputs': ['⚔️', '🏰'], 'output': '👑', 'name': 'Crown'},
  {'inputs': ['👑', '🔮'], 'output': '🧙', 'name': 'Wizard'},
  {'inputs': ['🧙', '⚡'], 'output': '🌟', 'name': 'Star Magic'},
  {'inputs': ['🌟', '🌟'], 'output': '🌌', 'name': 'Galaxy'},

  // ── Tier 5: Food ─────────────────────────────────────────────────────────
  {'inputs': ['🌱', '☀️', '💧'], 'output': '🍎', 'name': 'Apple'},
  {'inputs': ['🌴', '☀️', '💧'], 'output': '🍌', 'name': 'Banana'},
  {'inputs': ['🌿', '☀️', '💧'], 'output': '🥦', 'name': 'Broccoli'},
  {'inputs': ['🍎', '🔥'], 'output': '🍏', 'name': 'Cooked Apple'},
  {'inputs': ['🌾', '🔥'], 'output': '🍞', 'name': 'Bread'},
  {'inputs': ['🌱', '🌱', '☀️'], 'output': '🌾', 'name': 'Wheat'},
  {'inputs': ['🍯', '🌾'], 'output': '🍰', 'name': 'Cake'},
  {'inputs': ['🧊', '🍎'], 'output': '🧃', 'name': 'Juice'},

  // ── Tier 6: Weather & Space ───────────────────────────────────────────────
  {'inputs': ['☀️', '🌧️'], 'output': '🌈', 'name': 'Rainbow'},
  {'inputs': ['🌌', '☀️'], 'output': '🌞', 'name': 'Solar System'},
  {'inputs': ['🌌', '❄️'], 'output': '☄️', 'name': 'Comet'},
  {'inputs': ['☄️', '🌍'], 'output': '🌍', 'name': 'Earth (Reborn)'},
  {'inputs': ['🌌', '💧'], 'output': '🪐', 'name': 'Planet'},
  {'inputs': ['🌞', '🪐'], 'output': '🚀', 'name': 'Rocket'},
  {'inputs': ['🚀', '🌌'], 'output': '👨‍🚀', 'name': 'Astronaut'},
];
